language: cpp
cache: ccache
sudo: true
dist: trusty

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then  sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y  ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    sudo apt-get update ;

    sudo apt-get install gcc-6 g++-6 ;
    sudo update-alternatives ;
    sudo update-alternatives --remove-all gcc ;
    sudo update-alternatives --remove-all g++ ;
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 20 ;
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 20 ;
    sudo update-alternatives --config gcc ;
    sudo update-alternatives --config g++ ;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then  sudo apt-get update -d  ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" &&  ]; then  sudo apt-get update -d  ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update          ; fi


install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then  sudo apt-get install build-essential pkg-config cmake libwxgtk3.0-dev libftdi-dev freeglut3-dev zlib1g-dev libusb-1.0-0-dev  libdc1394-22-dev libavformat-dev libswscale-dev libassimp-dev libjpeg-dev libopencv-dev libgtest-dev libeigen3-dev libsuitesparse-dev libpcl-all libopenni2-dev libudev-dev gdb libboost-python-dev libpython-dev python-numpy -y ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap homebrew/science   ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install eigen          ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then /usr/bin/yes | pip uninstall numpy; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install opencv         ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install assimp         ; fi

script:
  - bash .travis.sh

matrix:
  include:
  - compiler: gcc
    os: linux
    env: TASK="build" CCACHE_SLOPPINESS=pch_defines,time_macros
  - compiler: gcc
    os: linux
    env: TASK="test" CCACHE_SLOPPINESS=pch_defines,time_macros
  - compiler: clang
    os: linux
    env: TASK="build" CCACHE_SLOPPINESS=pch_defines,time_macros
  - compiler: clang
    os: linux
    env: TASK="test" CCACHE_SLOPPINESS=pch_defines,time_macros
  - compiler: gcc
    os: osx
    env: TASK="test" CCACHE_SLOPPINESS=pch_defines,time_macros
  - compiler: clang
    os: osx
    env: TASK="test" CCACHE_SLOPPINESS=pch_defines,time_macros
