language: cpp
cache: ccache
sudo: false
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'ppa:v-launchpad-jochen-sprickerhof-de/pcl'
    packages:
    - g++-6
    - clang-3.8
    - build-essential
    - pkg-config
    - cmake
    - libwxgtk3.0-dev
    - libftdi-dev
    - freeglut3-dev
    - zlib1g-dev
    - libusb-1.0-0-dev
    - libdc1394-22-dev
    - libavformat-dev
    - libswscale-dev
    - libassimp-dev
    - libjpeg-dev
    - libopencv-dev
    - libgtest-dev
    - libeigen3-dev
    - libsuitesparse-dev
    - libpcl-all
    - libopenni2-dev
    - libudev-dev
    - gdb
    - libboost-python-dev
    - libpython-dev python-numpy 
    - lcov
    
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update          ; fi


install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew tap homebrew/science ;
    brew install eigen ;
    /usr/bin/yes | pip uninstall numpy ;
    brew install opencv ;
    brew install assimp ;
    fi
  - if [ "$BUILD_TYPE" == "Coverage" ]; then
    gem install coveralls-lcov ;
    fi


after_success:
 - if [ "$BUILD_TYPE" == "Coverage" ]; then bash scripts/coveralls_submit.sh fi

script:
  - bash .travis.sh

matrix:
  include:
  - compiler: gcc
    os: linux
    env: TASK="build" CCACHE_SLOPPINESS=pch_defines,time_macros
  - compiler: gcc
    os: linux
    env: TASK="test" CCACHE_SLOPPINESS=pch_defines,time_macros
  - compiler: clang
    os: linux
    env: TASK="build" CCACHE_SLOPPINESS=pch_defines,time_macros
  - compiler: clang
    os: linux
    env: TASK="test" CCACHE_SLOPPINESS=pch_defines,time_macros
  - compiler: gcc
    os: osx
    env: TASK="test" CCACHE_SLOPPINESS=pch_defines,time_macros
  - compiler: clang
    os: osx
    env: TASK="test" CCACHE_SLOPPINESS=pch_defines,time_macros
  - compiler: gcc
    os: linux
    env: TASK="test" BUILD_TYPE=Coverage CCACHE_SLOPPINESS=pch_defines,time_macros
